SearchBayesianSkopt: Resuming 'MatrixFactorization_BPR_Cython_Recommender' Failed, no such file exists.
SearchBayesianSkopt: Config 0 Exception. Config: {'sgd_mode': 'adagrad', 'epochs': 1500, 'num_factors': 182, 'batch_size': 32, 'positive_reg': 0.002152855095477557, 'negative_reg': 5.495567039345356e-05, 'learning_rate': 0.012795084546815208} - Exception: Traceback (most recent call last):
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 297, in _fit_model
    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/Recommenders/MatrixFactorization/Cython/MatrixFactorization_Cython.py", line 169, in fit
    super(MatrixFactorization_BPR_Cython, self).fit(**key_args)
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/Recommenders/MatrixFactorization/Cython/MatrixFactorization_Cython.py", line 57, in fit
    from Recommenders.MatrixFactorization.Cython.MatrixFactorization_Cython_Epoch import MatrixFactorization_Cython_Epoch
ModuleNotFoundError: No module named 'Recommenders.MatrixFactorization.Cython.MatrixFactorization_Cython_Epoch'

SearchBayesianSkopt: Resuming 'MatrixFactorization_BPR_Cython_Recommender' Failed, no such file exists.
SearchBayesianSkopt: Config 0 Exception. Config: {'sgd_mode': 'adam', 'epochs': 1500, 'num_factors': 165, 'batch_size': 128, 'positive_reg': 3.109777231594006e-05, 'negative_reg': 7.934699874390279e-05, 'learning_rate': 0.05228717705459538} - Exception: Traceback (most recent call last):
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 297, in _fit_model
    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/Recommenders/MatrixFactorization/Cython/MatrixFactorization_Cython.py", line 169, in fit
    super(MatrixFactorization_BPR_Cython, self).fit(**key_args)
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/Recommenders/MatrixFactorization/Cython/MatrixFactorization_Cython.py", line 57, in fit
    from Recommenders.MatrixFactorization.Cython.MatrixFactorization_Cython_Epoch import MatrixFactorization_Cython_Epoch
ModuleNotFoundError: No module named 'Recommenders.MatrixFactorization.Cython.MatrixFactorization_Cython_Epoch'

SearchBayesianSkopt: Config 1 Exception. Config: {'sgd_mode': 'adam', 'epochs': 1500, 'num_factors': 179, 'batch_size': 32, 'positive_reg': 0.0008701445757251114, 'negative_reg': 0.00044877760158154123, 'learning_rate': 0.0552377787933375} - Exception: Traceback (most recent call last):
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 297, in _fit_model
    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/Recommenders/MatrixFactorization/Cython/MatrixFactorization_Cython.py", line 169, in fit
    super(MatrixFactorization_BPR_Cython, self).fit(**key_args)
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/Recommenders/MatrixFactorization/Cython/MatrixFactorization_Cython.py", line 57, in fit
    from Recommenders.MatrixFactorization.Cython.MatrixFactorization_Cython_Epoch import MatrixFactorization_Cython_Epoch
ModuleNotFoundError: No module named 'Recommenders.MatrixFactorization.Cython.MatrixFactorization_Cython_Epoch'

SearchBayesianSkopt: Config 2 Exception. Config: {'sgd_mode': 'adam', 'epochs': 1500, 'num_factors': 130, 'batch_size': 16, 'positive_reg': 0.00018162851703802286, 'negative_reg': 0.007782312579725486, 'learning_rate': 0.0005954498173546816} - Exception: Traceback (most recent call last):
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 468, in _objective_function
    result_df, recommender_instance = self._evaluate_on_validation(current_fit_hyperparameters_dict, was_already_evaluated_flag, was_already_evaluated_index)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 326, in _evaluate_on_validation
    recommender_instance, train_time = self._fit_model(current_fit_hyperparameters)
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/HyperparameterTuning/SearchAbstractClass.py", line 297, in _fit_model
    recommender_instance.fit(*self.recommender_input_args.FIT_POSITIONAL_ARGS,
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/Recommenders/MatrixFactorization/Cython/MatrixFactorization_Cython.py", line 169, in fit
    super(MatrixFactorization_BPR_Cython, self).fit(**key_args)
  File "/Users/jodyrobertobattistini/PycharmProjects/rec-sys-challenge/Recommenders/MatrixFactorization/Cython/MatrixFactorization_Cython.py", line 57, in fit
    from Recommenders.MatrixFactorization.Cython.MatrixFactorization_Cython_Epoch import MatrixFactorization_Cython_Epoch
ModuleNotFoundError: No module named 'Recommenders.MatrixFactorization.Cython.MatrixFactorization_Cython_Epoch'

SearchBayesianSkopt: Search interrupted. No valid config was found during the initial random initialization
